apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.msName }}-service
spec:
  ports:
    - port: {{ .Values.common.port }}
      protocol: TCP
      targetPort: 3000
  selector:
    app: {{ .Values.common.msName }}
